# Generated by Django 5.2.14 on 2026-07-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admincredential_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
