# Generated by Django 5.2.14 on 2026-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inquiry_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=255)),
                ('problem_desc', models.TextField()),
                ('resolution_title', models.CharField(max_length=255)),
                ('resolution_desc', models.TextField()),
                ('stats', models.CharField(max_length=100)),
                ('latency', models.CharField(max_length=100)),
            ],
        ),
    ]
