# Generated by Django 5.2.14 on 2026-07-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_problemresolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capability',
        ),
    ]
