# Generated by Django 5.2.14 on 2026-07-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_capability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='history',
        ),
        migrations.AddField(
            model_name='about',
            name='commitment',
            field=models.TextField(default='Our focus is on delivering high quality development, timely delivery, and long term support. As a trusted product based organization, we ensure that every solution we build from ERP systems to mobile applications is engineered to absorb massive concurrency and scale effortlessly.'),
        ),
        migrations.AddField(
            model_name='about',
            name='values',
            field=models.TextField(default='Engineered with uncompromising precision. We value bulletproof safety, high concurrency, clean procedural pipelines, and high-fidelity aesthetics across every system.'),
        ),
        migrations.AddField(
            model_name='about',
            name='who_we_are',
            field=models.TextField(default='Zenelait Infotech specializes in building custom software products that empower startups, SMEs, and large enterprises. We bridge the gap between complex business challenges and innovative technology solutions.'),
        ),
    ]
